"""tokens, settings, and token_id on visitor_session_tokens

Revision ID: 003
Revises: 002
Create Date: 2026-06-29
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID, JSONB


revision = "003"
down_revision = "002"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # tokens — every session binds to exactly one of these.
    # kind='card' rows are minted per NFC tap.
    # kind='link' rows are pre-generated by the owner for sharing.
    op.create_table(
        "tokens",
        sa.Column(
            "id",
            UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column("token_hash", sa.String(64), nullable=False, unique=True),
        sa.Column("kind", sa.String(16), nullable=False),
        sa.Column("mode", sa.String(32), nullable=False),
        sa.Column("label", sa.String(255), nullable=True),
        sa.Column("tap_count", sa.Integer(), nullable=False, server_default=sa.text("0")),
        sa.Column("active", sa.Boolean(), nullable=False, server_default=sa.text("true")),
        sa.Column("revoked", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_reason", sa.String(255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("kind IN ('card', 'link')", name="ck_tokens_kind"),
        sa.CheckConstraint(
            "mode IN ('dating', 'mix', 'friendship', 'professional')",
            name="ck_tokens_mode",
        ),
    )
    op.create_index("ix_tokens_token_hash", "tokens", ["token_hash"])
    op.create_index("ix_tokens_kind", "tokens", ["kind"])

    # settings — simple key/value for owner-controlled runtime state.
    # Right now: active_mode for the NFC card.
    op.create_table(
        "settings",
        sa.Column("key", sa.String(64), primary_key=True),
        sa.Column("value", JSONB(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
    )

    # Seed the active_mode setting. Default friendship — least edgy default,
    # safe if the owner forgets to set it before handing the card around.
    op.execute(
        "INSERT INTO settings (key, value) VALUES ('active_mode', '\"friendship\"'::jsonb)"
    )

    # Wire visitor_session_tokens to tokens. No real data yet → drop and recreate.
    op.drop_index("ix_vst_token_hash", table_name="visitor_session_tokens")
    op.drop_index("ix_vst_visitor_id", table_name="visitor_session_tokens")
    op.drop_table("visitor_session_tokens")

    op.create_table(
        "visitor_session_tokens",
        sa.Column(
            "id",
            UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "visitor_id",
            UUID(as_uuid=True),
            sa.ForeignKey("visitors.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "token_id",
            UUID(as_uuid=True),
            sa.ForeignKey("tokens.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column("token_hash", sa.String(64), nullable=False, unique=True),
        sa.Column(
            "issued_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("superseded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("superseded_grace_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked", sa.Boolean(), nullable=False, server_default=sa.text("false")),
    )
    op.create_index("ix_vst_visitor_id", "visitor_session_tokens", ["visitor_id"])
    op.create_index("ix_vst_token_id", "visitor_session_tokens", ["token_id"])
    op.create_index("ix_vst_token_hash", "visitor_session_tokens", ["token_hash"])


def downgrade() -> None:
    op.drop_index("ix_vst_token_hash", table_name="visitor_session_tokens")
    op.drop_index("ix_vst_token_id", table_name="visitor_session_tokens")
    op.drop_index("ix_vst_visitor_id", table_name="visitor_session_tokens")
    op.drop_table("visitor_session_tokens")

    op.create_table(
        "visitor_session_tokens",
        sa.Column(
            "id",
            UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "visitor_id",
            UUID(as_uuid=True),
            sa.ForeignKey("visitors.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("token_hash", sa.String(64), nullable=False, unique=True),
        sa.Column(
            "issued_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("superseded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("superseded_grace_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked", sa.Boolean(), nullable=False, server_default=sa.text("false")),
    )
    op.create_index("ix_vst_visitor_id", "visitor_session_tokens", ["visitor_id"])
    op.create_index("ix_vst_token_hash", "visitor_session_tokens", ["token_hash"])

    op.drop_table("settings")
    op.drop_index("ix_tokens_kind", table_name="tokens")
    op.drop_index("ix_tokens_token_hash", table_name="tokens")
    op.drop_table("tokens")